source 'https://rubygems.org'

gem 'json'
gem 'rake'
gem 'sequel'
gem 'sinatra'
gem 'singleton'

group :development, :test do
  gem 'minitest'
  gem 'rerun'
  gem 'rubocop'
  gem 'rubocop-minitest'
  gem 'rubocop-rake'
end
